name: download-artifact
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dawidd6/action-download-artifact@v2
      with:
        workflow: homepage-screenshot.yaml