# Manual started workflow
# This is the simplest for of running the Cypress tests in Github actions
name: homepage-screenshot-from-upload
on:
  workflow_dispatch:
  # repository_dispatch:
  # # push:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron: '10 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          mkdir -p /home/runner/work/cypress-gha-digimod/cypress-gha-digimod/testing/cypress/e2e/__image_snapshots__
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: homepage-screenshot.yaml
           # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: /home/runner/work/cypress-gha-digimod/cypress-gha-digimod/testing/cypress/e2e/__image_snapshots__
      - shell: bash
        run: |
          cd /home/runner/work/cypress-gha-digimod/cypress-gha-digimod/testing/cypress/e2e/__image_snapshots__
          mv cypress-screenshots/* .
          rmdir cypress-screenshots
      - name: Front page smoke tests
        uses: cypress-io/github-action@v5
        id: homepage-screenshot
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: false
        with:
        # No recording of results in the cloud
          record: false
        # We need to force the install due to version checking  
          install-command: npm ci -f
          working-directory: testing
          browser: firefox
          spec: cypress/e2e/homepage-screenshot-test.cy.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots-failed
          path: /home/runner/work/cypress-gha-digimod/cypress-gha-digimod/testing/cypress/e2e/__image_snapshots__
          if-no-files-found: error # 'warn' or 'error' are also available, defaults to `warn`, also `ignore`
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          name: cypress-screenshots-failed